USE loja_inteligente;

ALTER TABLE vendas
  ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 6) NULL AFTER local_venda,
  ADD COLUMN IF NOT EXISTS longitude DECIMAL(10, 6) NULL AFTER latitude,
  ADD COLUMN IF NOT EXISTS cidade VARCHAR(120) NULL AFTER longitude,
  ADD COLUMN IF NOT EXISTS bairro VARCHAR(120) NULL AFTER cidade,
  ADD COLUMN IF NOT EXISTS regiao VARCHAR(120) NULL AFTER bairro,
  ADD COLUMN IF NOT EXISTS estado VARCHAR(50) NULL AFTER regiao,
  ADD COLUMN IF NOT EXISTS cep VARCHAR(20) NULL AFTER estado,
  ADD COLUMN IF NOT EXISTS endereco_formatado VARCHAR(255) NULL AFTER cep;
